Remove no longer needed str_split_once feature
This fixes:
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/lib.rs:39:12
   |
39 | #![feature(str_split_once)]
   |            ^^^^^^^^^^^^^^

warning: the feature `str_split_once` has been stable since 1.52.0 and no longer requires an attribute to enable